version: '2'
services:
    dounya-app:
        image: dounya
        external_links:
            - dounya-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=dounya
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dounya-mongodb:
        extends:
            file: mongodb.yml
            service: dounya-mongodb
