version: '2'
services:
    dounya-mongodb:
        container_name: dounya-mongodb
        image: mongo:3.3.9
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/dounya/mongodb/:/data/db/
